name: RunicChat
version: ${project.version}
main: com.runicrealms.plugin.chat.RunicChat
api-version: 1.13
authors: [ RunicStudios ]
softdepend: [ PlaceholderAPI ]
depend: [ RunicCommon ]
description: Chat Plugin for Runic Realms
website: https://runicrealms.com/
permissions:
  runicchat.default:
    children:
      runicchat.command.example: true
    default: true
  runicchat.admin:
    children:
      runicchat.command.example: true
      runicchat.default: true
    default: op